services:
  # =========================================================
  # 🌐 Frontend (client-prod)
  # =========================================================
  - type: web
    name: client-prod
    env: docker
    plan: free
    dockerfilePath: ./client/Dockerfile.prod
    envVars:
      - key: NODE_ENV
        value: production

      - key: VITE_API_URL
        fromService:
          type: web
          name: server-prod
          property: hostUrl

  # =========================================================
  # ⚙️ Backend API (server-prod)
  # =========================================================
  - type: web
    name: server-prod
    env: docker
    plan: free
    dockerfilePath: ./server/Dockerfile.prod

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-prod
          property: connectionString

      - key: CORS_ORIGINS
        fromService:
          type: web
          name: client-prod
          property: hostUrl

  # =========================================================
  # 🗄️ Database (postgres-prod)
  # =========================================================
database:
  - type: postgres
    name: postgres-prod
    env: docker
    plan: free
    image: postgres:16.10-alpine
    dockerCommand: postgres

    envVars:
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false

    disk:
      name: postgres_prod_data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
  