name: Mirror Repository

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_REPO_URL: "git@github.com:EpitechPGE45-2025/G-ING-900-PAR-9-1-legacy-14.git"

jobs:
  mirror:
    name: Mirror the repository files to another repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
